# Netlify Build Settings
[build]
  publish = "dist/client"
  command = "npx convex deploy --cmd 'npm run build'"

# Catch-all - serve React SPA for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
